### ISSUE TITLE
iPhone 5 Video thumbnails distorted

### ISSUE THREAD

**Issue by mattkasner** [somasole/SomaSole#102]
![img_1833](https://cloud.githubusercontent.com/assets/19822593/16740795/83427432-4755-11e6-9b55-aeeb0895aef1.PNG)

Stretched Vertically

**Comment by mrigdon-zz** [comment]
this one is tricky.we download these images directly from YouTube so at the moment we're stuck with the resolution they give us. May be able to provide our own image, but that would require some rewriting. I'll look into the ratio though. Fucking iPhone 5.

**Comment by mattkasner** [comment]
So you use the YouTube thumbnails for the video page thumbnails?

**Comment by mrigdon-zz** [comment]
yup
