### ISSUE TITLE
Set aside workouts and add "starter" workouts 

### ISSUE THREAD

**Issue by mattkasner** [somasole/SomaSole#35]
WorkoUts to set aside:
Get functional 
Obliques
Sweat
Power Up

**Comment by mrigdon-zz** [comment]
just to confirm, the ones listed above are the **_free_** ones?

**Comment by mrigdon-zz** [comment]
reopening due to confusion

**Comment by mrigdon-zz** [comment]
Starter Workouts:

Full Body Burn
New You
