### ISSUE TITLE
Add 'Link Length" festure to setup in workout circuits

### ISSUE THREAD

**Issue by mattkasner** [somasole/SomaSole#36]
Need to identify the length of the link used with the setup provided

**Comment by mrigdon-zz** [comment]
Could you be more specific/provide a mockup? @mattkasner

**Comment by mattkasner** [comment]
Basically I just need to have the words "short" or "long" before or
accompanying the picture of the foot setup during the setup portions of the
workouts

**Comment by mrigdon-zz** [comment]
Okay I think accompanying it is a better call. Do you want the text above or below the image?

**Comment by mattkasner** [comment]
Below

**Comment by mrigdon-zz** [comment]
merging issue with setup images
