### ISSUE TITLE
Can't read entirety of some descriptions in "Timed/Guided"

### ISSUE THREAD

**Issue by mattkasner** [somasole/SomaSole#85]
If description for movements in “Timed/Guided” is too long, it get cut off. 

Possible Fixes:
Scroll down,
Take over entire screen

**Comment by mrigdon-zz** [comment]
Pretty sure u can scroll thru it right now. Maybe I'm wrong?

**Comment by mattkasner** [comment]
Can't scroll at the moment.

**Comment by mrigdon-zz** [comment]
Weird, pretty sure the scrolling works on my phone. I'll look into it though
