### ISSUE TITLE
Fix Setups

### ISSUE THREAD

**Issue by mattkasner** [somasole/SomaSole#87]
**Ab Shred**
- [x] Change circuit 3 to Setup3Long
- [x] Change “Hip Extension - Knee Up” into two movements: “Hip Extension - Knee Up” and    Hip Extension - Knee Up (Left)”  --> @mattkasner Do you have images for both? Or do you want me to just use the same image for both? Not seeing the left one atm. -->@mrigdon The left is in the google doc along with the right under the general "Hip Extension - Knee Up" folder

**Anchor Abs**
- [x] Change both circuits to Setup13Short

**Armageddon**
- [x] Change circuit 1 to Setup13Short

**Back to Back**
- [x] Change circuit to Setup1Short

**Booty Blaster**
- [x] Change circuit 1 to Setup1Short

**Boulder Shoulders**
- [x] Change “Plank Delt Row” into two movements: “Plank Delt Row (Right)” and Plank Delt Row (Left)”. --> @mattkasner same as comment in Ab Shred -->@mrigdon The left is in the google doc along with the right under the general “Plank Delt Row” folder
- [x] Change Circuit 2 to Setup1Short

**Cool Down**
- [x] Change circuit 2 to Setup13Short

**Ground Attack**
- [x] Change circuit 2 to Setup13Short

**Lean Legs**
- [x] Change “Hip Extension - Knee Up” into two movements: “Hip Extension - Knee Up” and    Hip Extension - Knee Up (Left)” @mattkasner --> same as comment in Ab Shred-->@mrigdon The left is in the google doc along with the right under the general "Hip Extension - Knee Up" folder
- [x] Change GIF for “Reverse Lunge (Left)” [the current one I provided uploaded incorrectly] @mattkasner --> is the correct one online now? --> @mrigdon yes
- [x] Change circuit 3 to Setup11Short

**Stretch**
- [x] “Hip Abduction” is incorrect. The movement is “Hip Rotation” (left and right) --> @mattkasner so the movement should be changed just for this workout, or rename Hip Abduction to Hip Rotation for all movements? --> @mrigdon it should be changed just for both the movement and workout

**Upper Body Blast**
- [x] Change circuit 2 to Setup1Short
- [x] Change circuit 3 to Setup14Short

**New You**
- [x] Change circuit 2 to Setup13Short
- [x] For the second movement in the second circuit, it should be “anchored leg circle” not “leg circle”. They are different movements.

**Comment by mrigdon-zz** [comment]
Please post bulleted list in comments of all setups incorrect, and their corrected ones. Thanks.

**Comment by mrigdon-zz** [comment]
@mattkasner bump

**Comment by mattkasner** [comment]
**Ab Shred**
	-Change circuit 3 to Setup3Long
	-Change “Hip Extension - Knee Up” into two movements: “Hip Extension - Knee Up” and 	Hip Extension - Knee Up (Left)”

**Anchor Abs**
	-Change both circuits to Setup13Short

**Armageddon**
	-Change circuit 1 to Setup13Short

**Back to Back**
	-Change circuit to Setup1Short

**Booty Blaster**
	-Change circuit 1 to Setup1Short

**Boulder Shoulders**
	-Change “Plank Delt Row” into two movements: “Plank Delt Row (Right)” and Plank Delt Row (Left)”.
-Change Circuit 2 to Setup1Short

**Cool Down**
	-Change circuit 2 to Setup13Short


**Ground Attack**
	-Change circuit 2 to Setup13Short

**InTENsity**
	OK

**Jump Training**
	OK

**Lean Legs**
	-Change “Hip Extension - Knee Up” into two movements: “Hip Extension - Knee Up” and 	Hip Extension - Knee Up (Left)”
	-Change GIF for “Reverse Lunge (Left)” [the current one I provided uploaded incorrectly]
	-Change circuit 3 to Setup11Short

**Plank**
	OK

**Pre-Party**
	OK

**Stretch**
	-“Hip Abduction” is incorrect. The movement is “Hip Rotation” (left and right)

**Upper Body Blast**
	-Change circuit 2 to Setup1Short
	-Change circuit 3 to Setup14Short
____________

**Full Body Burn**
	OK


**New You**
-Change circuit 2 to Setup13Short
-For the second movement in the second circuit, it should be “anchored leg circle” not “leg circle”. They are different movements.

**Comment by mrigdon-zz** [comment]
(note to self) check setup 1 short
