### ISSUE TITLE
Higher Quality "Lock" image

### ISSUE THREAD

**Issue by mattkasner** [somasole/SomaSole#91]
The image used to show that the workout or video is locked is too low res., especially on iPad

**Comment by mrigdon-zz** [comment]
I use [this site](https://icons8.com/web-app/new-icons/all) for practically every icon. 100x100 ones are free, but u gotta be a premium member. Would u be down for that? Here's the pricing: https://icons8.com/paid-license-99/#/

**Comment by mattkasner** [comment]
Ya just get the 7 icons package
