### ISSUE TITLE
Implementing Profile Picture

### ISSUE THREAD

**Issue by mattkasner** [somasole/SomaSole#93]
In the profile picture creation, if the user does not allow for the use of the "photos", they can't take a picture and submit it. Is this correct?

And when a person navigates to fix the issue in settings, they have to restart the login process. Can we make this less clunky?

**Comment by mrigdon-zz** [comment]
Not possible. This is the only way to allow users to take pictures or access their library in 3rd party apps

**Comment by mattkasner** [comment]
alrighty
